<?php

/*
	*** actual list is there
	*** https://udger.com/resources/ua-list/os
	***
*/

return array (

    'android'    			=> 'Android',
    'android 5.0'    		=> 'Android TV',
    'android 8.0.0'    		=> 'Android 8',
    'android 7.1'    		=> 'Android 7.1',
    'android 7.0'    		=> 'Android 7',
    'android 6.0'    		=> 'Android 6',
    'android 5.1'    		=> 'Android 5.1',
    'android 5.0'    		=> 'Android 5',
    'android 4.4'    		=> 'Android 4.4',
    'android 4.3'    		=> 'Android 4.3',
    'android 4.2'   	 	=> 'Android 4.2',
    'android 4.1.1'    		=> 'Android 4.1',
    'android 4.1'    		=> 'Android 4.1',
    'android 4.0.1'    		=> 'Android 4',
    'android-4.0.3'    		=> 'Android 4',
    'android 4.0.3'    		=> 'Android 4',
    'android 3.2'    		=> 'Android 3',
    'android 3.0'    		=> 'Android 3',
    'android 2.3.7'    		=> 'Android 2',
    'android 2.3.5'    		=> 'Android 2',
    'android 2.3.3'    		=> 'Android 2',
    'android 2.2.1'    		=> 'Android 2',
    'android 2.2'    		=> 'Android 2',
    'Android 2.1'    		=> 'Android 2',
    'Android Eclair'    	=> 'Android 2',
    'Android 2.1-update1'   => 'Android 2',
	
    'windows iot 10.0'  	=> 'Windows IoT',
    'windows nt 6.4'    	=> 'Windows 10',
    'windows nt 10.0'   	=> 'Windows 10',
    'windows nt 6.3'    	=> 'Windows 8.1',
    'windows nt 6.2'    	=> 'Windows 8',
    'windows nt 6.1'    	=> 'Windows 7',
    'windows phone 10.0'	=> 'Windows 10 Mobile',
    'windows phone os 7.5'  => 'Windows Phone 7',
    'windows phone 8.0'    	=> 'Windows Phone 8',
    'windows phone 8.1'    	=> 'Windows Phone 8.1',
    'windows mobile'    	=> 'Windows Mobile',
    'windows phone 6.5.3.5' => 'Windows Mobile',
    'windows nt 6.0'    	=> 'Windows Vista',
    'windows nt 5.2'    	=> 'Windows 2003',
    'windows nt 5.0'    	=> 'Windows 2000',
    'windows 2000'    		=> 'Windows 2000',
    'windows nt 5.1'    	=> 'Windows XP',
    'windows nt 4.0'   		=> 'Windows NT 4.0',
    'winnt4.0'         		=> 'Windows NT 4.0',
    'winnt 4.0'        		=> 'Windows NT',
    'winnt'            		=> 'Windows NT',
    'windows me' 		   	=> 'Windows ME',
    'win 9x 4.90'    		=> 'Windows ME',
    'windows 98'        	=> 'Windows 98',
    'win98'             	=> 'Windows 98',
    'windows 95'        	=> 'Windows 95',
    'win95'             	=> 'Windows 95',
    'windows'           	=> 'Unknown Windows OS',
    'windows ce 5.1'    	=> 'Windows CE',
    'windows ce'    		=> 'Windows CE',

    'intel mac os x 10_9'   => 'OS X 10.9 Mavericks',
    'intel mac os x 10_9_1' => 'OS X 10.9 Mavericks',
    'intel mac os x 10_8'   => 'OS X 10.8 Mountain Lion',
    'intel mac os x 10.7'   => 'OS X 10.7 Lion',
    'intel mac os x 10_7_2' => 'OS X 10.7 Lion',
    'intel mac os x 10_6_2' => 'OS X 10.6 Snow Leopard',
    'intel mac os x 10.6'   => 'OS X 10.6 Snow Leopard',
    'intel mac os x 10.5'   => 'OS X 10.5 Leopard',
    'intel mac os x 10_5_5' => 'OS X 10.5 Leopard',
    'intel mac os x 10.4'   => 'OS X 10.4 Tiger',
    'ppc mac os x 10_4_11'  => 'OS X 10.4 Tiger',	
    'os x'              	=> 'Mac OS X',
    'ppc mac'           	=> 'Power PC Mac',
    'cpu iphone os 11_0 like mac os x'    	=> 'iOS 11',
    'cpu iphone os 10_0 like mac os x'    	=> 'iOS 10',
    'cpu os 9_0 like mac os x'    			=> 'iOS 9',
    'cpu iphone os 9_2 like mac os x'    	=> 'iOS 9',
    'cpu iphone os 8_3 like mac os x'    	=> 'iOS 8',
    'cpu iphone os 8_0_2 like mac os x'    	=> 'iOS 8',
    'cpu os 8_0 like mac os x'    			=> 'iOS 8',
    'cpu iphone os 8_0 like mac os x'    	=> 'iOS 8',
    'cpu os 7_0_2 like mac os x'    		=> 'iOS 7',
    'cpu os 7_0 like mac os x'    			=> 'iOS 7',
    'cpu iphone os 7_0 like mac os x'    	=> 'iOS 7',
    'cpu iphone os 6_0 like mac os x'    	=> 'iOS 6',
    'cpu os 6_0 like mac os x'    			=> 'iOS 6',
	
    'cros i686 9.10.0'    			=> 'Chrome OS',
    'cros armv7l 5500.100.6'    	=> 'Chrome OS',
    'cros armv7l 6158.70.0'    		=> 'Chrome OS',

    'freebsd'           	=> 'FreeBSD',
    'ppc'               	=> 'Macintosh',
    'ubuntu'            	=> 'Ubuntu',
    'debian'            	=> 'Debian',
    'linux'             	=> 'Linux',
    'sunos'             	=> 'Sun Solaris',
    'beos'              	=> 'BeOS',
    'apachebench'       	=> 'ApacheBench',
    'aix'               	=> 'AIX',
    'irix'              	=> 'Irix',
    'osf'               	=> 'DEC OSF',
    'hp-ux'             	=> 'HP-UX',
    'netbsd'            	=> 'NetBSD',
    'bsdi'              	=> 'BSDi',
    'openbsd'           	=> 'OpenBSD',
    'gnu'               	=> 'GNU/Linux',
    'unix'              	=> 'Unknown Unix OS',
    
    'symbian'           	=> "Symbian",
    'SymbianOS'         	=> "SymbianOS",
    'elaine'            	=> "Palm",
    'palm'              	=> "Palm",
    'series60'          	=> "Symbian S60",
    'xbox'    				=> 'Xbox 360 Dashboard',
    'xbox one'    			=> 'Xbox OS',
	
);
?>